#!/usr/bin/env python3
"""
dedup_payments.py
=================
Auto-deduplication script for PaymentTransaction records.

Rules implemented:
  1. Same invoice, one PENDING + one SUCCESS (any method) → cancel the PENDING one.
  2. Same invoice, multiple PENDING PAY_LATER records → keep the newest, cancel the rest.
  3. Same invoice, multiple PENDING RAZORPAY records (no SUCCESS) → keep the newest, cancel the rest.

Usage (run from backend folder with venv active):
  python scripts/dedup_payments.py              # dry-run (shows what would be changed)
  python scripts/dedup_payments.py --apply      # actually apply the changes
  python scripts/dedup_payments.py --apply --verbose

LOCAL database: postgresql://palei_user:palei_pass@localhost:5433/palei_solutions
VPS   database: postgresql://bibek_user:<pass>@localhost:5432/bibek_enterprises
                Set DATABASE_URL env var to override (do not edit this file for VPS).
"""

import argparse
import asyncio
import logging
import os
import sys
from datetime import datetime, timezone

# ── Make sure the backend app package is importable ────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, BACKEND_DIR)

from sqlalchemy import select, func, text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("dedup_payments")


# ── DB URL ─────────────────────────────────────────────────────────────────────
def _get_db_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if url:
        logger.info(f"Using DATABASE_URL from env: {url.split('@')[-1]}")
        return url
    # local default
    url = "postgresql://palei_user:palei_pass@localhost:5433/palei_solutions"
    logger.info(f"Using local default DB: {url.split('@')[-1]}")
    return url


def _async_url(url: str) -> str:
    return url.replace("postgresql://", "postgresql+asyncpg://", 1)


# ── IST timestamp for notes ────────────────────────────────────────────────────
def _now_ist_str() -> str:
    try:
        import zoneinfo
        ist = zoneinfo.ZoneInfo("Asia/Kolkata")
        return datetime.now(ist).strftime("%Y-%m-%d %H:%M:%S IST")
    except Exception:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ── Core dedup logic ───────────────────────────────────────────────────────────
async def run_dedup(apply: bool, verbose: bool) -> None:
    db_url = _get_db_url()
    engine = create_async_engine(_async_url(db_url), echo=False)
    Session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    mode = "APPLY" if apply else "DRY-RUN"
    logger.info(f"=== dedup_payments.py — mode: {mode} ===")

    cancelled_total = 0
    now_ist = _now_ist_str()

    async with Session() as db:
        # ── Rule 1: same invoice has ≥1 SUCCESS + ≥1 PENDING → cancel PENDING ──
        logger.info("Rule 1: cancel PENDING where same invoice already has a SUCCESS transaction …")

        # Find all (invoice_id) that have at least one SUCCESS
        success_invoice_ids_result = await db.execute(
            text("""
                SELECT DISTINCT invoice_id
                FROM payment_transactions
                WHERE status = 'SUCCESS'
                  AND is_active = TRUE
            """)
        )
        success_invoice_ids = [str(row[0]) for row in success_invoice_ids_result.fetchall()]

        if not success_invoice_ids:
            logger.info("  No invoices with SUCCESS transactions found.")
        else:
            logger.info(f"  Found {len(success_invoice_ids)} invoice(s) with a SUCCESS payment.")
            # For each such invoice, find all PENDING transactions
            pending_with_success_result = await db.execute(
                text("""
                    SELECT id, invoice_id, method, status, amount, created_at, notes
                    FROM payment_transactions
                    WHERE invoice_id = ANY(:ids)
                      AND status = 'PENDING'
                      AND is_active = TRUE
                    ORDER BY invoice_id, created_at
                """),
                {"ids": success_invoice_ids},
            )
            pending_rows = pending_with_success_result.fetchall()

            if not pending_rows:
                logger.info("  No PENDING duplicates found under Rule 1.")
            else:
                logger.info(f"  Found {len(pending_rows)} PENDING transaction(s) to cancel under Rule 1.")
                for row in pending_rows:
                    txn_id, inv_id, method, status, amount, created_at, notes = row
                    note_append = (
                        f" [Auto-cancelled by dedup script on {now_ist}"
                        f" — invoice already has a SUCCESS payment]"
                    )
                    new_notes = ((notes or "") + note_append)[:1000]
                    if verbose:
                        logger.info(
                            f"  → CANCEL txn {txn_id} | invoice {inv_id} | method={method}"
                            f" | amount={amount} | created={created_at}"
                        )
                    if apply:
                        await db.execute(
                            text("""
                                UPDATE payment_transactions
                                SET status = 'CANCELLED',
                                    is_active = FALSE,
                                    notes = :notes
                                WHERE id = :id
                            """),
                            {"id": str(txn_id), "notes": new_notes},
                        )
                    cancelled_total += 1

        # ── Rule 2: same invoice, multiple PENDING PAY_LATER → keep newest, cancel rest ──
        logger.info("Rule 2: deduplicate multiple PENDING PAY_LATER on same invoice …")

        multi_pay_later_result = await db.execute(
            text("""
                SELECT invoice_id, COUNT(*) AS cnt
                FROM payment_transactions
                WHERE method = 'PAY_LATER'
                  AND status = 'PENDING'
                  AND is_active = TRUE
                GROUP BY invoice_id
                HAVING COUNT(*) > 1
            """)
        )
        multi_pay_later = multi_pay_later_result.fetchall()

        if not multi_pay_later:
            logger.info("  No duplicate PENDING PAY_LATER found.")
        else:
            logger.info(f"  Found {len(multi_pay_later)} invoice(s) with duplicate PENDING PAY_LATER.")
            for inv_id_row, cnt in multi_pay_later:
                inv_id = str(inv_id_row)
                # Get all PENDING PAY_LATER for this invoice, ordered by created_at desc
                rows_result = await db.execute(
                    text("""
                        SELECT id, created_at, notes
                        FROM payment_transactions
                        WHERE invoice_id = :inv_id
                          AND method = 'PAY_LATER'
                          AND status = 'PENDING'
                          AND is_active = TRUE
                        ORDER BY created_at DESC
                    """),
                    {"inv_id": inv_id},
                )
                rows = rows_result.fetchall()
                # Keep the first (newest), cancel the rest
                keep_id = str(rows[0][0])
                to_cancel = rows[1:]
                if verbose:
                    logger.info(f"  Invoice {inv_id}: keeping PAY_LATER {keep_id}, cancelling {len(to_cancel)} older record(s).")
                for row in to_cancel:
                    txn_id = str(row[0])
                    old_notes = row[2]
                    note_append = (
                        f" [Auto-cancelled by dedup script on {now_ist}"
                        f" — duplicate PAY_LATER, kept newest {keep_id}]"
                    )
                    new_notes = ((old_notes or "") + note_append)[:1000]
                    if verbose:
                        logger.info(f"    → CANCEL PAY_LATER {txn_id}")
                    if apply:
                        await db.execute(
                            text("""
                                UPDATE payment_transactions
                                SET status = 'CANCELLED',
                                    is_active = FALSE,
                                    notes = :notes
                                WHERE id = :id
                            """),
                            {"id": txn_id, "notes": new_notes},
                        )
                    cancelled_total += len(to_cancel)

        # ── Rule 3: same invoice, multiple PENDING RAZORPAY (no SUCCESS) → keep newest ──
        logger.info("Rule 3: deduplicate multiple PENDING RAZORPAY on same invoice (no SUCCESS) …")

        multi_rzp_result = await db.execute(
            text("""
                SELECT invoice_id, COUNT(*) AS cnt
                FROM payment_transactions
                WHERE method = 'RAZORPAY'
                  AND status = 'PENDING'
                  AND is_active = TRUE
                GROUP BY invoice_id
                HAVING COUNT(*) > 1
            """)
        )
        multi_rzp = multi_rzp_result.fetchall()

        if not multi_rzp:
            logger.info("  No duplicate PENDING RAZORPAY found.")
        else:
            logger.info(f"  Found {len(multi_rzp)} invoice(s) with duplicate PENDING RAZORPAY.")
            for inv_id_row, cnt in multi_rzp:
                inv_id = str(inv_id_row)
                # Skip if this invoice already has a SUCCESS (Rule 1 handles those)
                has_success_result = await db.execute(
                    text("""
                        SELECT COUNT(*) FROM payment_transactions
                        WHERE invoice_id = :inv_id AND status = 'SUCCESS' AND is_active = TRUE
                    """),
                    {"inv_id": inv_id},
                )
                has_success = has_success_result.scalar_one() > 0
                if has_success:
                    if verbose:
                        logger.info(f"  Invoice {inv_id}: skipped (already handled by Rule 1 — has SUCCESS).")
                    continue

                rows_result = await db.execute(
                    text("""
                        SELECT id, created_at, notes
                        FROM payment_transactions
                        WHERE invoice_id = :inv_id
                          AND method = 'RAZORPAY'
                          AND status = 'PENDING'
                          AND is_active = TRUE
                        ORDER BY created_at DESC
                    """),
                    {"inv_id": inv_id},
                )
                rows = rows_result.fetchall()
                keep_id = str(rows[0][0])
                to_cancel = rows[1:]
                if verbose:
                    logger.info(f"  Invoice {inv_id}: keeping RAZORPAY {keep_id}, cancelling {len(to_cancel)} older record(s).")
                for row in to_cancel:
                    txn_id = str(row[0])
                    old_notes = row[2]
                    note_append = (
                        f" [Auto-cancelled by dedup script on {now_ist}"
                        f" — duplicate PENDING RAZORPAY, kept newest {keep_id}]"
                    )
                    new_notes = ((old_notes or "") + note_append)[:1000]
                    if verbose:
                        logger.info(f"    → CANCEL RAZORPAY {txn_id}")
                    if apply:
                        await db.execute(
                            text("""
                                UPDATE payment_transactions
                                SET status = 'CANCELLED',
                                    is_active = FALSE,
                                    notes = :notes
                                WHERE id = :id
                            """),
                            {"id": txn_id, "notes": new_notes},
                        )
                    cancelled_total += len(to_cancel)

        # ── Commit ─────────────────────────────────────────────────────────────
        if apply:
            await db.commit()
            logger.info(f"✅ Committed. Total transactions cancelled: {cancelled_total}")
        else:
            await db.rollback()
            logger.info(
                f"DRY-RUN complete. Would cancel {cancelled_total} transaction(s)."
                " Re-run with --apply to actually make changes."
            )

    await engine.dispose()


# ── Entry point ────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Deduplicate payment transactions (PENDING + SUCCESS on same invoice)."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Actually apply changes. Without this flag, runs in dry-run mode.",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        default=False,
        help="Print each transaction being cancelled.",
    )
    args = parser.parse_args()
    asyncio.run(run_dedup(apply=args.apply, verbose=args.verbose))


if __name__ == "__main__":
    main()
